notifications:
  email: false

matrix:
  include:
    - os: linux
      sudo: required
    - os: osx

language: node_js

node_js:
  - "v7.9.0"  # Current stable Electron version

install:
  - ./.travis/install.sh
  - npm install
  - npm run rebuild
