matrix:
  include:
    - os: linux
      sudo: required
    - os: osx
      sudo: required

language: node_js

node_js:
  - "7.9.0"  # Current stable Electron version

install:
  - ./.travis/install.sh
